# config/meta.yml

meta_product_name: "MyLocalScene"
meta_title: "MyLocalScene - Explorez la scène locale !"
meta_description: " Un nouvel outil pour les musiciens et les passionnés. Découvrez, échangez, partagez."
meta_image: "MLS.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
